### ISSUE TITLE
How to reset chat

### ISSUE THREAD

**Issue by OguzEkinci** [leegeunhyeok/react-native-zendesk-messaging#18]

**Comment by leegeunhyeok** [comment]
currently, reset or clear chat history isn't supported yet.

ref: https://support.zendesk.com/hc/fr/community/posts/4659977184026-iOS-SDK-Reset-Zendesk-Messaging-History-Change-Channel-Key-Programmatically

**Comment by OguzEkinci** [comment]
so how to now ticket resolved or closed ?

**Comment by leegeunhyeok** [comment]
> so how to now ticket resolved or closed ? or how to do this "The active ticket/session would need to be solved and closed out in order to restart the bot flow for authenticated users."

@OguzEkinci You can resolve or close tickets in Zendesk support dashboard

**Comment by OguzEkinci** [comment]
> > so how to now ticket resolved or closed ? or how to do this "The active ticket/session would need to be solved and closed out in order to restart the bot flow for authenticated users."
> 
> @OguzEkinci You can resolve or close tickets in Zendesk support dashboard

i know that, im saying, when i did resolve or close ticket's status, how can i understand in mobile "it is resolved"

**Comment by leegeunhyeok** [comment]
Hmm.. I tried to find docs about clear history, but couldn't find anything. Same as that answer, there doesn't seem to be a way to delete chat history.

Just seems that users can start a new chat after finishing the previous one.

- Start chat
- (...)
- End chat (or end of bot flow)
- Can start new chat
  - but previous chat history still exist

Sorry about that, if you need to clear history of chat, request feature to Zendesk community.
